# Exploratory Data Analysis

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

## Transforming the user data

In [2]:
df = pd.read_csv("../data/raw/users_metadata_messy.csv")
df

,user_id,age,gender,height_m,weight_kg,experience_level,workout_frequency_days_week,fat_percentage
0,U0001,47,Male,1.72,75.8,Advanced,2,21.3
1,U0002,34,Female,1.42,78.7,Advanced,5,20.0
2,U0003,40,Male,1.71,75.2,Advanced,5,27.8
3,U0004,23,Female,1.98,83.1,Beginner,4,15.6
4,U0005,39,Male,1.49,78.1,Advanced,2,21.5
...,...,...,...,...,...,...,...,...
1231,U0894,50,Male,1.83,72.8,Beginner,5,18.0
1232,U0693,44,Male,1.66,NaN,Beginner,3,NaN
1233,U0728,19,Male,1.84,84.0,Beginner,5,14.2
1234,U0363,31,F,1.89,49.1,Beginner,5,24.5
1235,U0597,41,Female,1.82,96.6,Beginner,5,7.5

In [3]:
df.duplicated().sum()

36

In [4]:
df.drop_duplicates()

,user_id,age,gender,height_m,weight_kg,experience_level,workout_frequency_days_week,fat_percentage
0,U0001,47,Male,1.72,75.8,Advanced,2,21.3
1,U0002,34,Female,1.42,78.7,Advanced,5,20.0
2,U0003,40,Male,1.71,75.2,Advanced,5,27.8
3,U0004,23,Female,1.98,83.1,Beginner,4,15.6
4,U0005,39,Male,1.49,78.1,Advanced,2,21.5
...,...,...,...,...,...,...,...,...
1195,U1196,27,Female,1.61,100.1,expert,5,33.4
1196,U1197,31,Male,1.68,82.9,Beginner,3,22.4
1197,U1198,53,Female,1.88,107.4,Advanced,3,15.0
1198,U1199,33,Female,1.64,72.6,Intermediate,2,53.0
1199,U1200,35,Female,1.65,83.5,advanced,4,26.6

In [5]:
df.shape

(1236, 8)

In [6]:
df = df.set_index("user_id")

In [7]:
df

,age,gender,height_m,weight_kg,experience_level,workout_frequency_days_week,fat_percentage
user_id,,,,,,,
U0001,47,Male,1.72,75.8,Advanced,2,21.3
U0002,34,Female,1.42,78.7,Advanced,5,20.0
U0003,40,Male,1.71,75.2,Advanced,5,27.8
U0004,23,Female,1.98,83.1,Beginner,4,15.6
U0005,39,Male,1.49,78.1,Advanced,2,21.5
...,...,...,...,...,...,...,...
U0894,50,Male,1.83,72.8,Beginner,5,18.0
U0693,44,Male,1.66,NaN,Beginner,3,NaN
U0728,19,Male,1.84,84.0,Beginner,5,14.2
U0363,31,F,1.89,49.1,Beginner,5,24.5
U0597,41,Female,1.82,96.6,Beginner,5,7.5

## Age

In [8]:
df["age"].min()

18

In [9]:
df["age"].max()

59

In [10]:
df["age"].isnull().sum()

0

In [11]:
df["age"].mean()

38.333333333333336

## Gender

In [12]:
df.loc["U0054"] # whitespacing issue here

age                                      45
gender                              Female
height_m                               1.61
weight_kg                              84.5
experience_level               Intermediate
workout_frequency_days_week               3
fat_percentage                          9.5
Name: U0054, dtype: object

In [13]:
df["gender"] = df["gender"].str.strip()

In [14]:
df["gender"]

user_id
U0001      Male
U0002    Female
U0003      Male
U0004    Female
U0005      Male
          ...
U0894      Male
U0693      Male
U0728      Male
U0363         F
U0597    Female
Name: gender, Length: 1236, dtype: object

In [15]:
df["gender"] = (
    df["gender"].str.strip()
    .str.upper()
    .replace({
        "M": "MALE",
        "F": "FEMALE"
    })
)

In [16]:
df['gender'] = df['gender'].str.strip().str.upper()

In [17]:
df["gender"].value_counts()

gender
MALE      667
FEMALE    569
Name: count, dtype: int64

In [18]:
df["gender"].isnull().sum()

0

In [19]:
df.loc["U0054"]

age                                      45
gender                               FEMALE
height_m                               1.61
weight_kg                              84.5
experience_level               Intermediate
workout_frequency_days_week               3
fat_percentage                          9.5
Name: U0054, dtype: object

### Height

In [20]:
df["height_m"].min()

1.41

In [21]:
df["height_m"].max()

2.475201301765503

In [22]:
df["height_m"].isnull().sum()

48

In [23]:
df["height_m"] = df.groupby("gender")["height_m"].transform(
    lambda x: x.fillna(x.median())
)

48 reported null values so we will use a metric to find out if they are male or female and then utilise the median value.

In [24]:
df["height_m"].isnull().sum()

0

### User ID

In [25]:
df.index

Index(['U0001', 'U0002', 'U0003', 'U0004', 'U0005', ' U0006 ', 'U0007',
       'U0008', ' U0009 ', ' U0010 ',
       ...
       'U0678', 'U0571', 'U0359', 'U0599', 'U0391', 'U0894', 'U0693', 'U0728',
       'U0363', 'U0597'],
      dtype='object', name='user_id', length=1236)

In [26]:
df.index = df.index.str.strip()

In [27]:
df.index.duplicated().sum()

36

In [28]:
df[df.index.duplicated(keep=False)].sort_index()

,age,gender,height_m,weight_kg,experience_level,workout_frequency_days_week,fat_percentage
user_id,,,,,,,
U0045,35,FEMALE,1.690000,90.0,Advanced,3,32.5
U0045,35,FEMALE,1.690000,90.0,Advanced,3,32.5
U0050,31,MALE,1.760000,61.0,Intermediate,4,57.0
U0050,31,MALE,1.760000,61.0,Intermediate,4,57.0
U0059,50,MALE,1.590000,78.5,Beginner,3,22.3
...,...,...,...,...,...,...,...
U0975,35,MALE,1.720000,71.8,Intermediate,2,9.3
U1121,33,FEMALE,1.810000,86.3,Intermediate,5,19.1
U1121,33,FEMALE,1.810000,86.3,Intermediate,5,19.1
U1179,57,FEMALE,2.351437,73.2,Intermediate,4,25.9
U1179,57,FEMALE,2.351437,73.2,Intermediate,4,25.9

In [29]:
df = df[~df.index.duplicated(keep='first')]

In [30]:
df[df.index.duplicated(keep=False)].sort_index()

Empty DataFrame
Columns: [age, gender, height_m, weight_kg, experience_level, workout_frequency_days_week, fat_percentage]
Index: []

kept the first occurrence of the duplicated data and dropped the rest.

### Workout Frequency Days Week

In [31]:
df["workout_frequency_days_week"].max()

5

In [32]:
df["workout_frequency_days_week"].min()

2

In [33]:
df["workout_frequency_days_week"].mean().round()

3.0

In [34]:
df["workout_frequency_days_week"].isna().sum()

0

### Fat percentage

In [35]:
df["fat_percentage"].min()

3.1

In [36]:
df["fat_percentage"].max()

69.0

In [37]:
df["fat_percentage"].isna().sum()

71

In [38]:
df["fat_percentage"] = df.groupby(["gender", "experience_level"])["fat_percentage"].transform(
    lambda x: x.fillna(x.mean())
)

/var/folders/_f/zrnhp13d691b515f0j7qny4h0000gn/T/ipykernel_8891/1278100010.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["fat_percentage"] = df.groupby(["gender", "experience_level"])["fat_percentage"].transform(

In [39]:
df["fat_percentage"].isna().sum()

0

This bases the fat percentage on the average of the gender and the level of experience.

### Experience level

In [40]:
df["experience_level"] = df["experience_level"].str.strip()

/var/folders/_f/zrnhp13d691b515f0j7qny4h0000gn/T/ipykernel_8891/3306273245.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["experience_level"] = df["experience_level"].str.strip()

In [41]:
df["experience_level"].unique()

array(['Advanced', 'Beginner', 'mid', 'Intermediate', 'B', 'beginner',
       'ADV', 'INT', 'advanced', 'expert', 'intermediate', 'Beginer'],
      dtype=object)

In [42]:
df["experience_level"] = (
    df["experience_level"]
    .str.upper()
    .replace({
        "MID": "INTERMEDIATE",
        "ADV": "ADVANCED",
        "BEGINER": "BEGINNER",
        "B": "BEGINNER",
        "INT": "INTERMEDIATE",
        "EXPERT": "ADVANCED"
    })
)



df["experience_level"].unique()

/var/folders/_f/zrnhp13d691b515f0j7qny4h0000gn/T/ipykernel_8891/384282723.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["experience_level"] = (

array(['ADVANCED', 'BEGINNER', 'INTERMEDIATE'], dtype=object)

In [43]:
df.isna().sum()

age                             0
gender                          0
height_m                        0
weight_kg                      60
experience_level                0
workout_frequency_days_week     0
fat_percentage                  0
dtype: int64

### Weight

In [44]:
train = df[df["weight_kg"].notna()]
test = df[df["weight_kg"].isna()]

features = ["height_m", "age"]

model = LinearRegression()
model.fit(train[features], train["weight_kg"])

df.loc[df["weight_kg"].isna(), "weight_kg"] = model.predict(test[features])

In [45]:
df["weight_kg"].isna().sum()

0

In [46]:
df

,age,gender,height_m,weight_kg,experience_level,workout_frequency_days_week,fat_percentage
user_id,,,,,,,
U0001,47,MALE,1.72,75.8,ADVANCED,2,21.3
U0002,34,FEMALE,1.42,78.7,ADVANCED,5,20.0
U0003,40,MALE,1.71,75.2,ADVANCED,5,27.8
U0004,23,FEMALE,1.98,83.1,BEGINNER,4,15.6
U0005,39,MALE,1.49,78.1,ADVANCED,2,21.5
...,...,...,...,...,...,...,...
U1196,27,FEMALE,1.61,100.1,ADVANCED,5,33.4
U1197,31,MALE,1.68,82.9,BEGINNER,3,22.4
U1198,53,FEMALE,1.88,107.4,ADVANCED,3,15.0
U1199,33,FEMALE,1.64,72.6,INTERMEDIATE,2,53.0
U1200,35,FEMALE,1.65,83.5,ADVANCED,4,26.6

In [47]:
df.to_csv('../data/processed/user_transformation.csv')